### PR TITLE
Add wrapper object that initialises and contains enricher and analyzer objects

### LINKED ISSUE #32: Add wrapper object that initialises and contains enricher and analyzer objects

### PR DESCRIPTION
**Pull request by ubyndr**
Resolves #32 

I have some uncertainty about the wrapper class; it might not align exactly with what you had in mind. Everything seems like working in the workflow you described. It would require some improvement though.

This is what I use in my tries;
```Python
import tabulate

from pandasaurus_cxg.enrichment_analysis import AnndataEnrichmentAnalyzer
from pandasaurus_cxg.graph_generator.graph_generator import GraphGenerator


aea = AnndataEnrichmentAnalyzer("test/data/modified_human_kidney.h5ad")
# aea = AnndataEnrichmentAnalyzer("test/data/human_kidney.h5ad")

print(aea.enricher_manager.contextual_slim_enrichment())

df = aea.analyzer_manager.co_annotation_report()
df = df.sort_values(["field_name1", "value1"]).reset_index(drop=True)
print(tabulate.tabulate(df, df.columns.tolist(), tablefmt="fancy_grid"))

gg = GraphGenerator(aea)
gg.generate_rdf_graph()
gg.set_label_adding_priority(["class", "cell_type", "subclass.l1", "subclass.l1", "subclass.full", "subclass.l2", "subclass.l3"])
gg.add_label_to_terms()
gg.enrich_rdf_graph()
# gg.save_rdf_graph(file_name="new_kidney", _format="ttl")
gg.visualize_rdf_graph(
    [
        "http://example.org/69fa1a0f-9839-4211-be06-7ff59f43bc7d",
    ],
    predicate=None,
    file_path="new_kidney.ttl",
)
```

### CODE REVIEW

**Comment by dosumis** [comment]
Getting 
> ImportError: requires pygraphviz http://pygraphviz.github.io/

But having problems installing locally

> Note: This error originates from the build backend, and is likely not a problem with poetry but with pygraphviz (1.11) not supporting PEP 517 builds. You can verify this by running 'pip wheel --use-pep517 "pygraphviz (==1.11)"'.


Also - feel like the `gg.visualize_rdf_graph` needs pydoc.  Not clear to me how we expect users to find IRIs for nodes.

**Comment by dosumis** [comment]
Hard to details of PR.  Seems to work apart from the import issue.  Happy to merge if this is fixed.  All other issues now in tickets which can be addressed in their own PRs.  Will note which ones I think should be fixed for a release.

**Comment by ubyndr** [comment]
> Happy for you to merge once imports fixed.

I've added a script to install dependencies. It sets couple of env variables to resolve the graphics issue. Should I merge this as it is or should I wait for you to confirm whether the script resolves your issue or not.

**Comment by dosumis** [comment]
> I've added a script to install dependencies. It sets couple of env variables to resolve the graphics issue. Should I merge this as it is or should I wait for you to confirm whether the script resolves your issue or not.

As long as you are confident you can make a build for release with this, I'm happy to merge.  It will probably still take some playing around for me to switch to doing poetry builds from Command Line.  Currently using PyCharm built-in.

**Pull request merged**
